# -*- coding: utf-8 -*-
"""Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ubbs9rZ6GDNAke1lLyWHuUnD7gzTLoiT
"""

# ==============================
# extract_zeus.py
# ==============================

import pandas as pd
import mysql.connector
from datetime import datetime


# ==============================
# 1. CONFIGURACIÓN DB
# ==============================
DB_CONFIG = {
    "host": "localhost",        # cambia si es remoto
    "user": "*****",
    "password": "*************",
    "database": "*************",      # nombre real
    "port": 3306
}


# ==============================
# 2. CONEXIÓN
# ==============================
def connect_db():
    try:
        conn = mysql.connector.connect(**DB_CONFIG)
        print("Conexión MySQL correcta")
        return conn
    except Exception as e:
        print("Error de conexión:", e)
        return None


# ==============================
# 3. CONSULTA PRINCIPAL
# ==============================
def get_bookings(conn):
    query = "SELECT b.idBooking, b.amount, b.cost, b.bookingCode, b.created, b.lang, b.ofice, t.adultsNum, t.childNum, t.tiketName, t.dateFrom, t.grupo, t.evId  FROM booking b inner join ticket_details t on b.idBooking=t.idBooking WHERE t.evId in(1920,184,546,1521,2663,26,554,248,247,607,840,2645,7,186,609) and b.status IN (0,2)"
    df = pd.read_sql(query, conn)
    print(f"Registros extraídos: {len(df)}")
    return df


# ==============================
# 5. GUARDAR CSV
# ==============================
def save_csv(df):

    filename = "ticket_details.csv"

    df.to_csv(filename, index=False)

    print(f"Archivo guardado: {filename}")


# ==============================
# 6. MAIN
# ==============================
def main():

    conn = connect_db()
    if conn is None:
        return

    df = get_bookings(conn)
    save_csv(df)
    conn.close()
    print("Conexión cerrada")


# ==============================
# 7. EJECUCIÓN
# ==============================
if __name__ == "__main__":
    main()
