# -*- coding: utf-8 -*-
"""Copia de predict.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ubbs9rZ6GDNAke1lLyWHuUnD7gzTLoiT
"""
# ==============================
# predict.py
# ==============================

import pandas as pd
import joblib


# ==============================
# 1. CARGAR MODELO
# ==============================
def load_model(path):

    model = joblib.load(path)
    print("Modelo cargado")

    return model


# ==============================
# 2. CARGAR DATASET
# ==============================
def load_data(path):

    df = pd.read_csv(path)
    df['date'] = pd.to_datetime(df['date'])

    return df


# ==============================
# 3. GENERAR FEATURES PARA MAÑANA
# ==============================
def build_features(ev_id, df):

    tomorrow = pd.Timestamp.today().normalize() + pd.Timedelta(days=1)

    weekday = tomorrow.dayofweek
    month = tomorrow.month

    # IMPORTANTE: usar toda la serie (no solo weekday)
    serie_hist = (
        df[df['evId'] == ev_id]
        .sort_values('date')
    )

    # ==============================
    # LAGS
    # ==============================
    lag_1 = serie_hist['demand'].iloc[-1]
    lag_7 = serie_hist['demand'].iloc[-7]
    lag_14 = serie_hist['demand'].iloc[-14]

    rolling_4 = (
        serie_hist['demand']
        .shift(1)
        .rolling(4)
        .mean()
        .iloc[-1]
    )

    rolling_8 = (
        serie_hist['demand']
        .shift(1)
        .rolling(8)
        .mean()
        .iloc[-1]
    )

    # ==============================
    # FEATURE FINAL
    # ==============================
    X_pred = pd.DataFrame([{
        'evId': ev_id,
        'is_zero': int(lag_1 == 0),
        'weekday': weekday,
        'month': month,
        'lag_1': lag_1,
        'lag_7': lag_7,
        'lag_14': lag_14,
        'rolling_4': rolling_4,
        'rolling_8': rolling_8
    }])

    return X_pred


# ==============================
# 4. PREDICCIÓN
# ==============================
def predict_demand(model, X_pred):

    pred = model.predict(X_pred)

    # evitar negativos
    pred = max(0, pred[0])

    return int(round(pred))


# ==============================
# 5. EJECUCIÓN PRINCIPAL
# ==============================
def main():

    MODEL_PATH = "best_model.pkl"
    DATA_PATH = "dataset_modelo.csv"

    # excursiones a predecir
    excursiones = [184, 546, 7, 26]

    model = load_model(MODEL_PATH)
    df = load_data(DATA_PATH)

    print("\nPREDICCIÓN PARA MAÑANA\n")

    for ev_id in excursiones:

        X_pred = build_features(ev_id, df)

        pred = predict_demand(model, X_pred)

        print(f"Excursión {ev_id} -> {pred} personas")


# ==============================
# 6. EJECUCIÓN
# ==============================
if __name__ == "__main__":
    main()