# -*- coding: utf-8 -*-
"""Copia de preprocess.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ubbs9rZ6GDNAke1lLyWHuUnD7gzTLoiT
"""

# ==============================
# preprocess.py
# ==============================

import pandas as pd
import numpy as np


# ==============================
# 1. CARGAR DATOS
# ==============================
def load_data(path):
    df = pd.read_csv(path)

    df['dateFrom'] = pd.to_datetime(df['dateFrom'], errors='coerce')
    df['created'] = pd.to_datetime(df['created'], errors='coerce')

    df = df.dropna(subset=['dateFrom'])

    # demanda total
    df['demand'] = df['adultsNum'].fillna(0) + df['childNum'].fillna(0)

    return df


# ==============================
# 2. AGRUPAR
# ==============================
def aggregate(df):

    df_grouped = df.groupby(['dateFrom', 'evId'], as_index=False)['demand'].sum()

    return df_grouped


# ==============================
# 3. GENERAR CALENDARIO
# ==============================
def generate_calendar(df_grouped):

    calendar = {
        7:   [0,1,2,3,4,5,6],
        840: [0,1,2,3,4,5,6],
        184: [0,1,2,3,4,5,6],
        546: [0,1,2,3,4,5,6],
        1920: [1,4],
        1922: [2],
        2663: [1],
        26:   [0,1,2,3,4,5],
        554:  [2,3,5],
        248:  [1,2],
        247:  [2,3,4]
    }

    start = df_grouped['dateFrom'].min()
    end = df_grouped['dateFrom'].max()

    all_dates = pd.date_range(start, end)

    result = []

    for ev, valid_days in calendar.items():

        valid_dates = [d for d in all_dates if d.weekday() in valid_days]

        temp = pd.DataFrame({
            'date': valid_dates,
            'evId': ev
        })

        merged = temp.merge(
            df_grouped,
            left_on=['date','evId'],
            right_on=['dateFrom','evId'],
            how='left'
        )

        merged = merged.drop(columns=['dateFrom'])

        # rellenar demanda
        merged['demand'] = merged['demand'].fillna(0)

        # flag ceros
        merged['is_zero'] = (merged['demand'] == 0).astype(int)

        result.append(merged)

    df_final = pd.concat(result)

    return df_final


# ==============================
# 4. FEATURES TEMPORALES
# ==============================
def add_time_features(df):

    df['weekday'] = df['date'].dt.dayofweek
    df['month'] = df['date'].dt.month

    df = df.sort_values(['evId','date'])

    return df


# ==============================
# 5. SERIES (CLAVE)
# ==============================
def create_series(df):

    df['series'] = df['evId'].astype(str) + "_" + df['weekday'].astype(str)

    return df


# ==============================
# 6. FEATURES DE HISTORIA
# ==============================
def add_lags(df):

    df['lag_1'] = df.groupby('series')['demand'].shift(1)
    df['lag_7'] = df.groupby('series')['demand'].shift(7)
    df['lag_14'] = df.groupby('series')['demand'].shift(14)

    df['rolling_4'] = (
        df.groupby('series')['demand']
        .transform(lambda x: x.shift(1).rolling(4).mean())
    )

    df['rolling_8'] = (
        df.groupby('series')['demand']
        .transform(lambda x: x.shift(1).rolling(8).mean())
    )

    return df


# ==============================
# 7. LIMPIAR DATOS
# ==============================
def clean_data(df):

    df = df.dropna()

    # eliminar excursiones con poca demanda
    mean_demand = df.groupby('evId')['demand'].mean()
    valid_ev = mean_demand[mean_demand >= 3].index

    df = df[df['evId'].isin(valid_ev)]

    return df


# ==============================
# 8. GUARDAR DATASET FINAL
# ==============================
def save_dataset(df, output_path):

    df.to_csv(output_path, index=False)

    print(f"💾 Dataset listo: {output_path}")


# ==============================
# 9. PIPELINE COMPLETO
# ==============================
def run_pipeline(input_path, output_path):

    print("Cargando datos...")
    df = load_data(input_path)

    print("Agrupando...")
    df_grouped = aggregate(df)

    print("Generando calendario...")
    df_final = generate_calendar(df_grouped)

    print("Añadiendo features temporales...")
    df_final = add_time_features(df_final)

    print("Creando series...")
    df_final = create_series(df_final)

    print("Añadiendo lags...")
    df_final = add_lags(df_final)

    print("Limpiando datos...")
    df_final = clean_data(df_final)

    print("Guardando dataset...")
    save_dataset(df_final, output_path)

    print("Pipeline completado")


# ==============================
# 10. EJECUCIÓN
# ==============================
if __name__ == "__main__":

    INPUT = "ticket_details.csv"
    OUTPUT = "dataset_modelo.csv"

    run_pipeline(INPUT, OUTPUT)