# -*- coding: utf-8 -*-
"""Copia de train_models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ubbs9rZ6GDNAke1lLyWHuUnD7gzTLoiT
"""

# ==============================
# train_models.py
# ==============================

import pandas as pd
import numpy as np
import joblib

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor, ExtraTreesRegressor, GradientBoostingRegressor

from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from catboost import CatBoostRegressor


# ==============================
# 1. CARGAR DATASET
# ==============================
def load_data(path):

    df = pd.read_csv(path)

    df['date'] = pd.to_datetime(df['date'])

    return df


# ==============================
# 2. PREPARAR DATOS
# ==============================
def prepare_data(df):

    X = df.drop(['demand','date','series'], axis=1)
    y = df['demand']

    # split temporal
    split = int(len(df) * 0.8)

    X_train = X.iloc[:split]
    X_test = X.iloc[split:]

    y_train = y.iloc[:split]
    y_test = y.iloc[split:]

    return X_train, X_test, y_train, y_test


# ==============================
# 3. MODELOS
# ==============================
def get_models():

    models = {

        "LinearRegression": LinearRegression(),

        "RandomForest": RandomForestRegressor(
            n_estimators=200,
            max_depth=10,
            random_state=42,
            n_jobs=-1
        ),

        "ExtraTrees": ExtraTreesRegressor(
            n_estimators=200,
            max_depth=10,
            random_state=42,
            n_jobs=-1
        ),

        "GradientBoosting": GradientBoostingRegressor(
            n_estimators=200,
            learning_rate=0.05,
            max_depth=5,
            random_state=42
        ),

        "XGBoost": XGBRegressor(
            n_estimators=300,
            learning_rate=0.05,
            max_depth=6,
            subsample=0.8,
            colsample_bytree=0.8,
            random_state=42
        ),

        "LightGBM": LGBMRegressor(
            n_estimators=300,
            learning_rate=0.05,
            max_depth=6,
            subsample=0.8,
            colsample_bytree=0.8,
            random_state=42
        ),

        "CatBoost": CatBoostRegressor(
            iterations=300,
            learning_rate=0.05,
            depth=6,
            loss_function='RMSE',
            verbose=0,
            random_state=42
        )
    }

    return models


# ==============================
# 4. EVALUACIÓN
# ==============================
def evaluate_models(models, X_train, X_test, y_train, y_test):

    results = []
    best_model = None
    best_mae = float("inf")

    for name, model in models.items():

        print(f"🔄 Entrenando {name}...")

        model.fit(X_train, y_train)

        y_pred = model.predict(X_test)

        mae = mean_absolute_error(y_test, y_pred)
        rmse = np.sqrt(mean_squared_error(y_test, y_pred))
        r2 = r2_score(y_test, y_pred)

        results.append({
            "Modelo": name,
            "MAE": mae,
            "RMSE": rmse,
            "R2": r2
        })

        # guardar mejor modelo
        if mae < best_mae:
            best_mae = mae
            best_model = model

    results_df = pd.DataFrame(results).sort_values("MAE")

    print("\n RESULTADOS:")
    print(results_df)

    return best_model, results_df


# ==============================
# 5. GUARDAR MODELO
# ==============================
def save_model(model, path):

    joblib.dump(model, path)

    print(f"Modelo guardado en: {path}")


# ==============================
# 6. MAIN
# ==============================
def main():

    DATA_PATH = "dataset_modelo.csv"
    MODEL_PATH = "best_model.pkl"

    print("Cargando datos...")
    df = load_data(DATA_PATH)

    print("Preparando datos...")
    X_train, X_test, y_train, y_test = prepare_data(df)

    print("Cargando modelos...")
    models = get_models()

    print("Evaluando modelos...")
    best_model, results_df = evaluate_models(
        models, X_train, X_test, y_train, y_test
    )

    print("\nMejor modelo seleccionado")

    save_model(best_model, MODEL_PATH)


# ==============================
# 7. EJECUCIÓN
# ==============================
if __name__ == "__main__":
    main()